### ISSUE TITLE
Use postres

### ISSUE THREAD

**Issue by dmtrKovalenko** [dmtrKovalenko/stand-bots#8]
Migrate from json-db to postgresql

**Comment by maximzhemerenko** [comment]
Может лучше заюзаем no-sql? 

Вот интересная штука
https://realm.io/blog/first-object-database-realm-node-js-server/

она не enterprise уровн но у нас тоже не enterprise ))

**Comment by dmtrKovalenko** [comment]
Нельзя потому что инстанс такой штуки будет умирать вместе с инстансами сервера :(
